branch-defaults:
  master:
    environment: null
global:
  application_name: moviequiz
  default_ec2_keyname: null
  default_platform: Tomcat 8 Java 8
  default_region: eu-central-1
  profile: eb-cli
  sc: git
