INSERT INTO MOVIES (MOVIE_ID, NAME, RELEASE_YEAR) VALUES (1, 'Star Wars', 1977);
INSERT INTO MOVIES (MOVIE_ID, NAME, RELEASE_YEAR) VALUES (2, 'I, Robot', 2004);
INSERT INTO MOVIES (MOVIE_ID, NAME, RELEASE_YEAR) VALUES (3, 'I am Legend', 2005);
INSERT INTO MOVIES (MOVIE_ID, NAME, RELEASE_YEAR) VALUES (4, 'Fight Club', 1993);